FROM node:19.8.1-alpine
ENV LISTEN_PORT=8000
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --silent && mv node_modules ../
COPY . .
RUN npm run build
COPY . .
CMD npm run start:prod

